# Generated by Django 4.1.1 on 2022-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
