# Generated by Django 4.1.1 on 2022-10-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitality', '0002_hotel_delete_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
